### ISSUE TITLE
Emacs freezes when manually playing a new song

### ISSUE THREAD

**Issue by guilherme-salome** [momomo5717/emms-player-simple-mpv#6]
Hi! I'm using Emacs 25.2.1 on a Mac HighSierra, and this is my configuration for emms + mpv:
```elisp
(require 'emms-setup)
(emms-minimalistic)
(add-to-list 'load-path "~/.emacs.d/emms-player-simple-mpv-master/")
;; Set MPV as default player
(require 'emms-player-simple-mpv)
(require 'emms-player-simple-mpv-control-functions) ;; This plugin provides control functions (e.g. ab-loop, speed, fullscreen).
(define-emms-simple-player-mpv my-mpv '(file url streamlist playlist)
  (concat "\\`\\(http[s]?\\|mms\\)://\\|"
	  (apply #'emms-player-simple-regexp
		 "aac" "pls" "m3u"
		 emms-player-base-format-list))
  "mpv" "--no-terminal" "--force-window=no" "--audio-display=no")
(setq emms-player-list '(emms-player-my-mpv))
;; Set up music folder
(setq emms-playlist-buffer-name "*Music*")
(setq emms-source-file-default-directory "/Users/guilhermesalome/Music/iTunes/iTunes Media/Music/")
(emms-add-directory-tree emms-source-file-default-directory)
```
I used a setup similar to this with mplayer, but switched to mpv because mplayer would display embedded album covers all the time (annoying, could not find a way to fix it).

The problem with what I have is that when I `M-x emms` (or `C-x b *Music*`), is that when hitting `RET` to a play a new song, Emacs will freeze. And it will stay frozen unless I hit `C-g` a lot of times. I am not sure what is causing this/how to solve. Any ideas? Or better configs?

Thanks for helping! :D

**Comment by guilherme-salome** [comment]
I just realized Emacs also freezes when a new song starts playing, even if automatically.

**Comment by momomo5717** [comment]
Hello @Salompas,

Thank you for opening this issue.

I use Emacs 25.3.1 and mpv 0.26.0 on El Capitan.
Sorry I can't test on HighSierra.

`emms-player-simple-mpv--socket-wait-file` might have failed to find a socket file.
Could you try the following in order to see if the function causes the issue?

``` elisp
(defvar emms-player-simple-mpv--socket-wait-file-test-timeout 10.0)

(defun emms-player-simple-mpv--socket-wait-file-test (process fname)
  (let ((counter 0.0)
        (timeout emms-player-simple-mpv--socket-wait-file-test-timeout)
        (dir (file-name-directory fname)))
    (unless (file-exists-p dir)
      (error "%s does not exist" dir))
    (while (and (eq (process-status process) 'run)
                (not (file-exists-p fname))
                (<= counter timeout))
      (cl-incf counter 0.05)
      (sit-for 0.05))
    (when (> counter timeout)
      (error "Failed to find the socket file: %s" fname))))

(advice-add 'emms-player-simple-mpv--socket-wait-file :override
            'emms-player-simple-mpv--socket-wait-file-test)
```

I hope this will be of some help.

**Comment by guilherme-salome** [comment]
Hi @momomo5717 thanks for the quick reply!

I added the code to my `init.el` file, and when I play something, and then try to move the cursor elsewhere, I do get the message `Failed to find the socket file`.

Do you have any idea how to fix this? Thanks for helping! :D

**Comment by momomo5717** [comment]
I'm sorry for my late reply.

Thank you for running the test config and sharing the result!

I added a new function to connect to mpv socket asynchronously. (101d120)
I hope it will work for you.

Thank you.

**Comment by guilherme-salome** [comment]
Works perfectly! Thanks for solving this @momomo5717 :D
